api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    show_webby: false

    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                -   application/json
        multipart:
            mime_types:
                - multipart/form-data

        graphql: ['application/graphql']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    graphql:
        enabled: true
