api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    show_webby: false
    enable_docs: '%kernel.debug%'
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                -   application/json
        multipart:
            mime_types:
                - multipart/form-data

        graphql: ['application/graphql']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    graphql:
        enabled: true

    # oauth:
    #     # To enable or disable OAuth.
    #     enabled: false

    #     # The OAuth client ID.
    #     clientId: ''

    #     # The OAuth client secret.
    #     clientSecret: ''

    #     # The OAuth type.
    #     type: 'oauth2'

    #     # The OAuth flow grant type.
    #     flow: 'application'

    #     # The OAuth token url.
    #     tokenUrl: '/oauth/v2/token'

    #     # The OAuth authentication url.
    #     authorizationUrl: '/oauth/v2/auth'

    #     # The OAuth scopes.
    #     scopes: []
