meilisearch:
    url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    indices:
        # Define entities or documents that should be indexed to Meilisearch.
        # See https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data
        - name: user
          class: App\Entity\User
          enable_serializer_groups: true
          serializer_groups: ["read:user:collection"]
          settings:
            searchableAttributes: ['*'] # Champs recherchables
            filterableAttributes: ['roles', 'isActive']  # Filtres possibles
            typoTolerance:
                enabled: true
                minWordSizeForTypos:
                    oneTypo:  3  # Taille minimale pour 1 faute de frappe
                    twoTypos: 3  # Taille minimale pour 2 fautes de frappe
            sortableAttributes: ['id:desc']           # Tri possible
            rankingRules:                              # Priorités de recherche
                - words
                - typo
                - proximity
                - sort
            stopWords: ['le', 'la', 'des', 'de', 'aux', 'au']  # Mots ignorés             # Mots ignorés
            synonyms:                                  # Synonymes
                admin: ['administrator', 'superuser']
        
        - name: society
          class: App\Entity\Society
          enable_serializer_groups: true
          serializer_groups: ["read:society:get", "read:society:collection"]
          settings:
            searchableAttributes: ['nom_society'] # Champs recherchables
            sortableAttributes: ['nom_society']           # Tri possible
            rankingRules:                              # Priorités de recherche
                - words
                - typo
                - proximity
            stopWords: ['le', 'la', 'de']             # Mots ignorés
        
        - name: offreEmploi
          class: App\Entity\OffreEmploi
          enable_serializer_groups: true
          serializer_groups: ['read:get:offre', 'read:collection:offre']
          settings:
            searchableAttributes: ['*'] # Champs recherchables
            sortableAttributes: ['id:desc']           # Tri possible
            typoTolerance:
                enabled: true
                minWordSizeForTypos:
                    oneTypo:    3  # Taille minimale pour 1 faute de frappe
                    twoTypos:   3  # Taille minimale pour 2 fautes de frappe
            rankingRules:                              # Priorités de recherche
                - words
                - typo
                - proximity
            stopWords: ['le', 'la', 'des', 'de', 'aux', 'au']  # Mots ignorés

    nbResults: 200
