old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        generate_pdf_send_email:
            connection:       default
            exchange_options: { name: 'pdf-email', type: direct }
    consumers:
        generate_pdf_send_email:
            connection:       default
            exchange_options: { name: 'pdf-email', type: direct }
            queue_options:    { name: 'pdf-email'}
            callback:         App\RabbitMq\Consumer\CreatePdfAndSendEmailConsumer
