old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        generate_pdf:
            connection:       default
            exchange_options: { name: 'generate-pdf', type: direct }
    consumers:
        generate_pdf:
            connection:       default
            exchange_options: { name: 'generate-pdf', type: direct }
            queue_options:    { name: 'generate-pdf'}
            callback:         App\RabbitMq\Consumer\GeneratePdfConsumer
