payum:
    storages:
        App\Entity\Payment: { doctrine: orm }

    security:
        token_storage:
            App\Entity\Token: { doctrine: orm }

    gateways:
        # offline:
        #     factory: offline
        default:
            factory: stripe_checkout
            publishable_key: '%publish_key%'
            secret_key: '%secret_key%'