version: '3.8'

services:
  database:
    container_name: mariadb
    image: mariadb:10.10.2
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: api-platform
      # MARIADB_USER: symfony
      # MARIADB_PASSWORD: secret
      # MARIADB_ROOT_PASSWORD: secret

    ports:
      - '3307:3306'
    volumes:
      - mariadb-data:/var/lib/mysql

  phpadmin:
    container_name: php_admin5
    image: bitnami/phpmyadmin:5.2.1
    environment:
      DATABASE_ALLOW_NO_PASSWORD: "yes"
      DATABASE_HOST: database
      # DATABASE_USER: root
      # DATABASE_PASSWORD: secret
    ports:
      - '8081:8080'
      - '8443:8443'
    depends_on:
      - database
  php:
    container_name: app
    build:
      context: ./.docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/offre.local
    depends_on:
      - database
      - phpadmin
      - meilisearch
    command: bash -c "php bin/console meili:create --env=test"
    # command: bash -c "ls -la /var/www/docker.local"
  meilisearch:
    image: getmeili/meilisearch:v1.4.0
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_API_KEY} # Clé secrète (remplacez-la)
      MEILI_ENV: development # Ou "production" en prod
      MEILI_NO_ANALYTICS: "true" # Désactive les analytics
    volumes:
      - meilisearch_data:/data.ms # Persistance des données
    ports:
      - "7700:7700" # Port exposé (HTTP)
    restart: unless-stopped

volumes:
  mariadb-data:
  meilisearch_data:
